
profiles: dev
#
#spring:
#  servlet:
#    multipart:
#      enabled: true
#      max-file-size: 10Mb
#      max-request-size: 100Mb
#
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://47.101.55.23:3306/uploadimage
#    username: root
##    password: sneakerhead
#    password: Hdd#51784
#    type: com.alibaba.druid.pool.DruidDataSource
#    # 连接池的配置信息
#    # 初始化大小，最小等待连接数量，最大等待连接数量，最大连接数
#    initialSize: 1
#    minIdle: 1
#    maxIdle: 5
#    maxActive: 20
#    # 配置获取连接等待超时的时间
#    maxWait: 60000
#    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#    timeBetweenEvictionRunsMillis: 60000
#    # 配置一个连接在池中最小生存的时间，单位是毫秒
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: SELECT 1 FROM DUAL
#    testWhileIdle: true
#    testOnBorrow: true
#    testOnReturn: false
#    # 打开PSCache，并且指定每个连接上PSCache的大小
#    poolPreparedStatements: false
#    maxPoolPreparedStatementPerConnectionSize: 20
#    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#    filters: stat,wall,log4j
#    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#    # 合并多个DruidDataSource的监控数据
#    #spring.datasource.useGlobalDataSourceStat=true

#qiniu:
#  accessKey: Y-73szeWRmCY2H8ivDNt_Kadn0uOYjqnOKmy81_2
#  secretKey: pSIvFSA0vJ71wezwfwYPkSTFXUKKyLiqqeV6F129
#  bucket: markdownimage
#  domain: http://pwmlkp28a.bkt.clouddn.com/
server:
  port: 6666


